version: '3'

includes:
  db:
    taskfile: ./db/Taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/Taskfile.yaml
    dir: ./app
  stack:
    taskfile: ./stack/Taskfile.yaml
    dir: ./stack
  image:
    taskfile: ./orch/task/Image.yaml
    internal: true

tasks:
  component:binaries:
    aliases: [cbs]
    cmds:
      - task: app:binaries

  component:packages:
    aliases: [cps]
    cmds:
      - task: db:images
      - task: app:images

  solution:packages:
    aliases: [sps]
    deps: [component:packages]
    cmds:
      - task: stack:images
