version: '3'

includes:
  db:
    taskfile: ./db/Taskfile.yaml
    dir: ./db
  app:
    taskfile: ./app/Taskfile.yaml
    dir: ./app
  stack:
    taskfile: ./stack/Taskfile.yaml
    dir: ./stack

tasks:
  part:binaries:
    aliases: [pb]
    cmds:
      - task: app:binaries
  part:packages:
    aliases: [pp]
    cmds:
      - task: db:images
      - task: app:images
  whole:packages:
    aliases: [wp]
    # deps: [part:packages]
    cmds:
      - task: stack:images
