version: '3'

vars:
  REPO_MODE: n/a  # n/a, ro, rw

tasks:
  binaries:
    cmd: go build -o rolevod main.go
  images:
    cmd: >-
      docker build ..
      --file Dockerfile
      --tag rolevod/app:latest
