version: '3'

vars:
  REPO_MODE: n/a  # n/a, ro, rw
  IMAGE: rolevod/app
  CID:
    sh: >-
      find ../lib .
      -name "*.go" -exec md5sum {} + -o
      -name "Dockerfile" -exec md5sum {} +
      | LC_ALL=C sort -k 2
      | md5sum
      | head -c 7

tasks:
  binary:
    aliases: [bin]
    cmd: go build -o rolevod main.go

  process:
    aliases: [proc, run]
    cmds:
      - go run github.com/jmattheis/goverter/cmd/goverter gen -g 'output:file ./generated.go' ./...
      - go run main.go

  image:
    status:
      - docker image inspect {{.IMAGE}}:{{.CID}}
    cmds:
      - task: :image:clean
        vars:
          IMAGE_KEY: "{{.IMAGE}}"
      - task: :image:build
        vars:
          IMAGE_HOME: app
          IMAGE_CTX: ..
          IMAGE_NAME: "{{.IMAGE}}"
          IMAGE_TAG: "{{.CID}}"
