version: '3'

vars:
  REPO_MODE: n/a  # n/a, ro, rw
  IMAGE: rolevod/postgres
  CID:
    sh: >-
      find postgres -type f -exec md5sum {} +
      | LC_ALL=C sort -k 2
      | md5sum
      | head -c 7

tasks:
  images:
    status:
      - docker image inspect {{.IMAGE}}:{{.CID}}
    cmds:
      - task: :image:clean
        vars:
          IMAGE_KEY: '{{.IMAGE}}'
      - task: :image:build
        vars:
          IMAGE_KEY: '{{.IMAGE}}'
          IMAGE_HOME: db/postgres
          IMAGE_NAME: '{{.IMAGE}}'
          IMAGE_TAG: '{{.CID}}'
