---
name: rolevod

networks:
  product:
    name: product
    external: false

services:
  storage:
    image: postgres:alpine
    networks:
      - product
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    labels:
      causality.key: rolevod/postgres

  database:
    image: rolevod/postgres:latest
    networks:
      - product
    depends_on:
      storage:
        condition: service_healthy
    command: >-
      --show-banner=false
      --classpath=/liquibase/changelog
      --changelog-file=dba/changelog.yaml
      --url=jdbc:postgresql://storage:5432/postgres
      --liquibase-schema-name=public
      --default-schema-name=public
      --username=postgres
      --password=password
      update
      -Ddatabase.name=rolevod
      -Downer.username=rolevod
      -Downer.password=rolevod
    labels:
      causality.key: rolevod/postgres

  schema:
    image: rolevod/postgres:latest
    networks:
      - product
    depends_on:
      database:
        condition: service_completed_successfully
    command: >-
      --show-banner=false
      --classpath=/liquibase/changelog
      --changelog-file=owner/changelog.yaml
      --url=jdbc:postgresql://storage:5432/rolevod
      --liquibase-schema-name=public
      --default-schema-name=rolevod
      --username=rolevod
      --password=rolevod
      update
      -Dschema.name=rolevod
    labels:
      causality.key: rolevod/postgres

  app:
    image: rolevod/app:latest
    networks:
      - product
    depends_on:
      schema:
        condition: service_completed_successfully
    ports:
      - "8080:8080"
    labels:
      causality.key: rolevod/app
 