= Конвейер (Pipeline)

Система, реализуемая для внедренцев.

.Ключевые принципы
****
Роботизированная заливка изменений::
Позволяет избежать ошибок/конкуренции и, как следствие, неоправданных потерь на загруженных ветках (например, main).
****

== Непрерывная интеграция (CI)

Артефакты собираем во всех окружениях, которые поддерживаются для разработчиков. Решение проверяем во всех окружениях, которые поддерживаются для клиентов.

=== В пределах разумного (sanity)

Запускаем анализ зависимостей, линтинг кодовой базы, компиляцию, прогоняем модульные тесты и собираем бинарники.

=== Убедительная (convincing)

Все перечисленное ранее. Плюс прогоняем интеграционные тесты, анализируем покрытие, публикуем бинарники и образы.

=== За пределами сомнений (beyond doubt)

Все перечисленное ранее. Плюс собираем стеки, прогоняем сквозные тесты, публикуем стеки.

== Частые вопросы (FAQ)

[qanda]
Почему обязательными статусными проверками назначены тестовые отчеты, а не тестовые джобы?::
Это дает свободу выбора структуры джобов, т.к. в различных планах сборки она может быть разной.

== Todo

. Релизная сборка
