= Конвейер (Pipeline)

Система, реализуемая для внедренцев.

.Ключевые принципы
****
Роботизированная заливка изменений::
Позволяет избежать ошибок/конкуренции и, как следствие, неоправданных потерь на загруженных ветках (например, main).
****

== Непрерывная интеграция (CI)

Планы делим на 2 категории:

. Проверяющие решение (solution)
. Проверяющие инструментарий (toolchain)

=== Проверка решения

Решение проверяем во всех окружениях, в которых его могут эксплуатировать клиенты.

==== В пределах разумного (sanity)

Запускаем анализ зависимостей, линтинг, компиляцию, прогоняем модульные тесты и собираем бинарники.

==== Убедительная (convincing)

Все перечисленное ранее. Плюс прогоняем интеграционные тесты, анализируем покрытие, публикуем бинарники, собираем и публикуем образы.

==== За пределами сомнений (beyond doubt)

Все перечисленное ранее. Плюс собираем стеки, прогоняем сквозные тесты, публикуем стеки.

=== Проверка инструментария

Инструментарий проверяем во всех окружениях, в которых его могут эксплуатировать разработчики.

==== В пределах разумного (sanity)

Запускаем линтинг исходного кода инструментария.

==== За пределами сомнений (beyond doubt)

Запускаем проверку работы всего инструментария и публикуем стеки.

== Частые вопросы (FAQ)

[qanda]
Почему обязательными статусными проверками назначены тестовые отчеты, а не тестовые джобы?::
Это дает свободу выбора структуры джобов, т.к. в различных планах сборки она может быть разной.

== Todo

. Релизная сборка
