= Инструментарий (Toolchain)

Система, реализуемая для разработчиков.

.Ключевые принципы
****
Единая обвязка для локальной разработки и непрерывной интеграции::
Семантика обвязки подразумевает набор предопределенных абстракций, артефакты которых последовательно конструируются в ходе сборки. Перед началом конструирования выполняются обязательные проверки. Примеры абстракций: кодовая база (codebase), бинарники (binaries), образы (images), стеки (stacks) и другие.

Контентная адресация (aka идентификация по содержимому)::
Контентная адресация (content addressability) делает конструирование артефактов *идемпотентным*. Для директорий с исходным кодом вычисляются их контентные идентификаторы (CID's). Затем вычисляются корневые идентификаторы решения и инструментария. Таким образом формируется 2 небольших дерева Меркла, хеши которых подставляются в качестве тегов/классификаторов артефактов соответствующих абстракций. Артефакт реконструируется, только когда его контентный идентификатор изменился.

Множественность окружений::
Инструментарий используется разработчиками в различных окружениях (envs). Ключевые окружения явно выделяются и проверяются в рамках непрерывной интеграции, устаревшие - снимаются с поддержки.
****

== Консольный интерфейс (CLI)

    ansible-playbook <abstraction>.yaml

== Todo

. Параллелизация модульных тестов
. Построение дерева хешей (взглянуть критически)
